### PR TITLE
why not

### PR DESCRIPTION
**Pull request by HeroEyad**
adding a gettime and settime to flxvideosprite because i think it can be put to use so why not (plus i found there is time in Video.hx so why not.

### CODE REVIEW

**Comment by MAJigsaw77** [comment]
Why not use the variables directly? `video.bitmap.time`

**Comment by MAJigsaw77** [comment]
It works the same way

**Comment by HeroEyad** [comment]
figured I'd use bitmap since it's already declared as a variable using Video but you already got a point.

**Comment by HeroEyad** [comment]
The idea of seeking and getting time just popped in my head.

**Comment by HeroEyad** [comment]
So i thought why not add it, it prob can be used.

**Comment by MAJigsaw77** [comment]
It's useless to have a function that does the same thing as the variable

**Comment by HeroEyad** [comment]
I mean you're right but, I thought it would be more safer to use a function logic with a small error handling.

It's up for you to make a decision. I'm just trying to add an Encapsulation and Consistency to both of the functions.

**Comment by MAJigsaw77** [comment]
> I mean you're right but, I thought it would be more safer to use a function logic with a small error handling.
> 
> It's up for you to make a decision. I'm just trying to add an Encapsulation and Consistency to both of the functions.

The error handling is really unnecessary though, I'll close this...

**Pull request closed without merging**
