### PR TITLE
Improve project settings

### PR DESCRIPTION
**Pull request by Redar13**
1. Make the manifest “libvlc” only for android, because it's only used there.
2. Add defines: "HXVLC_NO_PLAYLIST" & "HXVLC_PLAYLIST_PATH".

### CODE REVIEW

**Review by moxie-coder — APPROVED** [review]
this seems like it would fix compiling for Linux on Debian based systems, whereas Arch doesn't have this problem

**Comment by moxie-coder** [comment]
I know this because I learned that the hard way

**Comment by Redar13** [comment]
I just made this pull request because it stresses me out to have two folders with lua files in one of them, lol.

**Comment by Redar13** [comment]
Maybe I'm not even the only one.

**Review by PurSnake — APPROVED** [review]

**Review by mcagabe19 — CHANGES_REQUESTED** [review]
we do not allow this

**Pull request closed without merging**
